#include "AnalysisModel.hpp"
#include <sstream>
#include <iomanip>

namespace FEA {

std::string AnalysisModel::toInpString() const {
    std::stringstream ss;
    ss << "** CalculiX Input File generated by Structural FEA Suite\n";
    
    // Nodes
    ss << "*NODE, NSET=NALL\n";
    for (const auto& pair : nodes) {
        const Node& n = pair.second;
        ss << n.id << ", " << std::fixed << std::setprecision(6) 
           << n.x << ", " << n.y << ", " << n.z << "\n";
    }

    // Elements (simplified for prototype)
    for (const auto& pair : elements) {
        const Element& e = pair.second;
        ss << "*ELEMENT, TYPE=" << e.type << ", ELSET=E" << e.id << "\n";
        ss << e.id << ", ";
        for (size_t i = 0; i < e.nodeIds.size(); ++i) {
            ss << e.nodeIds[i] << (i == e.nodeIds.size() - 1 ? "" : ", ");
        }
        ss << "\n";
    }

    // Materials
    for (const auto& mat : materials) {
        ss << "*MATERIAL, NAME=" << mat.name << "\n";
        ss << "*ELASTIC\n";
        ss << mat.youngModulus << ", " << mat.poissonRatio << "\n";
        ss << "*DENSITY\n";
        ss << mat.density << "\n";
    }

    // Boundary Conditions
    ss << "*STEP\n*STATIC\n";
    ss << "*BOUNDARY\n";
    for (const auto& bc : constraints) {
        for (int dof : bc.dofs) {
            ss << bc.nodeId << ", " << dof << ", " << dof << ", " << bc.value << "\n";
        }
    }

    // Loads
    ss << "*CLOAD\n";
    for (const auto& load : loads) {
        if (load.fx != 0) ss << load.nodeId << ", 1, " << load.fx << "\n";
        if (load.fy != 0) ss << load.nodeId << ", 2, " << load.fy << "\n";
        if (load.fz != 0) ss << load.nodeId << ", 3, " << load.fz << "\n";
    }

    ss << "*NODE FILE\nU\n";
    ss << "*EL FILE\nS, E\n";
    ss << "*END STEP\n";

    return ss.str();
}

std::string AnalysisModel::toJson() const {
    nlohmann::json j;
    // Simple implementation for now
    j["node_count"] = nodes.size();
    j["element_count"] = elements.size();
    return j.dump();
}

void AnalysisModel::fromJson(const std::string& jsonStr) {
    auto j = nlohmann::json::parse(jsonStr);
    // Parsing logic would go here
}

} // namespace FEA
